### ISSUE TITLE
French quotes

### ISSUE THREAD

**Issue by akost** [matmuchrapna/typographic-quotes#3]
In French typography qoutes are separated by spaces from phrase inside. E. g. « monde ». 

There is also a space before an exclamation sign and a question sign. E. g. _Vous voulez me voir ?_

**Comment by iamstarkov** [comment]
Can you help me with identifying proper basement for this rule? Wikipedia telling me that this behavior is not dominant.

**Comment by akost** [comment]
Wikipedia:

http://en.wikipedia.org/wiki/Quotation_mark#French

http://fr.wikipedia.org/wiki/Guillemet#.C3.89criture_ou_typographie

http://french.about.com/library/writing/bl-punctuation.htm

> **Two-part punctuation marks**
> In French, a space is required both before and after all two- (or more) part punctuation marks and symbols, including : ; « » ! ? % $ #

PDF Book: http://jacques-andre.fr/faqtypo/lessons.pdf

Screenshot from the book:
(une espace normale -- a regular space, une espace insécable -- a non-breaking space)

![screen shot 2015-05-11 at 9 25 29 am](https://cloud.githubusercontent.com/assets/698174/7569762/e4a64910-f7bf-11e4-9e24-2092280e25e4.png)

**Comment by akost** [comment]
http://beranger.org/2013/05/13/french-typography-rules-and-the-epub-files/

**Comment by iamstarkov** [comment]
oh, shit. sorry for such huge delay. ping me next time

**Comment by iamstarkov** [comment]
started investigation, will keep you posted

**Comment by iamstarkov** [comment]
@akost can you code review #5?

**Comment by akost** [comment]
@iamstarkov sorry for being late.
#5 looks good to me.

**Comment by iamstarkov** [comment]
great, thanks!

**Comment by iamstarkov** [comment]
published in `v.1.2.2`
